name: Swift Full CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-check:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Swift
        run: swift --version

      - name: Check for dependency issues
        run: |
          cd udemy
          swift package resolve

      - name: Run static analysis
        run: swift package diagnose

      - name: Check formatting with swift-format
        run: |
          if which swift-format > /dev/null; then
            swift-format lint --recursive .
          else
            echo "swift-format not installed. Skipping..."
          fi

      - name: Run SwiftLint
        run: |
          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "SwiftLint not installed. Skipping..."
          fi

      - name: Run security check (Optional)
        run: |
          if which trivy > /dev/null; then
            trivy fs .
          else
            echo "Trivy not installed. Skipping security scan..."
          fi